### ISSUE TITLE
Broken link for design systems repo

### ISSUE THREAD

**Issue by guitheengineer** [JudeTejada/compiled#3]
Hey @JudeTejada, congrats for your project, really cool!

Just found a broken link for the following card
![image](https://user-images.githubusercontent.com/49620737/213274121-3f71a749-9e99-46a6-86a9-0510fcd45d03.png)

It should be https://designsystemsrepo.com/design-systems/

**Comment by JudeTejada** [comment]
Hey  @guilhermefront  👋

This is now fixed. Thank you!
